version: "3.9"
########################### NETWORKS

networks:
  wan:
    name: wan
    driver: bridge

  itflow-db:
    name: itflow-db
    external: false

########################### VOLUMES

volumes:
  itflow-db:

########################### ITFLOW
services:
  itflow:
    hostname: itflow
    container_name: itflow
    build:
      context: ./
    restart: unless-stopped
    networks:
      - wan
      - itflow-db
    ports:
      - "9090:8080"
    environment:
      - TZ=$TZ
      - ITFLOW_NAME=ITFlow
      - ITFLOW_URL=admin.$ROOT_DOMAIN
      - ITFLOW_PORT=8080
      - ITFLOW_REPO=github.com/r-o-k-u/itflow
      - ITFLOW_REPO_BRANCH=master
      - ITFLOW_LOG_LEVEL=info
      - ITFLOW_DB_HOST=$ITFLOW_DB_HOST
      - ITFLOW_DB_PASS=$ITFLOW_DB_PASS
    volumes:
      - ./itflow/:/var/www/html
